export * from './Navbar';
export * from './Section';
export * from './Naves';
export * from './Home';
export * from './LoginModal';
export * from './RegisterModal';
export * from './Text';
export * from './Pilotos';
export * from './Films';